predictions_path: "./results/predictions/E2_test_predictions.jsonl"
results_dir: "./results"

spider_db_dir: "./data/Spider/database"
spider_test_db_dir: "./data/Spider/test_database"
bird_train_db_dir: "./data/BIRD/train/train_databases"
bird_dev_db_dir: "./data/BIRD/dev/dev_databases"

execution_timeout: 30.0
